.\" Generated with Ronnjs 0.4.0
.\" http://github.com/kapouer/ronnjs
.
.TH "NODEQUAD" "1" "September 2014" "0.0.1" "nodequad"
.
.SH "NAME"
\fBnodequad\fR \-\- Communicate with an aeroquad vehicle from the command line
.
.SH "SYNOPSIS"
.
.nf
nodequad <command\.\.> [args\.\.]
nodequad \-\-list
nodequad \-\-probe \-\-connect
nodequad \-\-connect serial://115200@/dev/ttyACM0 \-\-sync config\.vehicle\.*
nodequad \-\-probe \-\-connect \-\-sync config\.vehicle\.pid\.roll [1\.1, 1\.2, 1\.3]
nodequad \-\-probe \-\-connect \-\-subscribe driver\.state\.connected
nodequad \-\-probe \-\-connect \-\-stream state\.gps\.*
.
.fi
.
.SH "VERSION"
0\.0\.1
.
.SH "DESCRIPTION"
nodequad is a command line utility to communicate with an Aeroquad vehicle\. It
supports most features of the API client\. This program is useful for basic interfacing
via shell scripts or exec\'ing from external applications that cannot use the API client\.
.
.SH "INTRODUCTION"
\fBnodequad \-\-connect serial://115200@/dev/ttyACM0\fR will connect to the
aeroquad at /dev/ttyACM0 at baudrate 115200 and terminate with a 0 exit code if successful, or non\-zero if
not successfull after a default timeout\. Note this URI will use the \'serial\' driver\.
.
.P
You can also list available interfaces for a given driver, using the \-\-list command\. The following example outputs a
JSON array for possible communication ports and exits: \fBnodequad \-\-list\fR\|\. You can also change the driver and protocol by using
the \fB\-\-driver <driver>\fR and \fB\-\-protocol <protocol>\fR options\.
.
.P
To probe for available devices on all recognized communication ports, use: \fBnodequad \-\-probe\fR\|\. A JSON array of possible
vehicles to connect to, including their respective URI will be output and the program will exit\. To connect to the first
found vehicle automatically (useful for quick testing), do the following: \fBnodequad \-\-probe \-\-connect\fR\|\. This will probe 
available ports, connect to the first vehicle (if found) and return a 0 exit code if successful\.
.
.P
That\'s the basics of connecting to vehicles\. Other commands allow you to monitor vehicle state, set flight configuration properties
and stream real\-time state information\. See the below examples and description for more information\.
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fB[\-\-driver <name|path>]\fR
The name of the driver from Aeroquad\.drivers or a path to a file that implements a driver interface\. Defaults to \'serial\' driver\.
.
.IP "\(bu" 4
\fB[\-\-protocol <name|path>]\fR
The name of the protocol from Aeroquad\.protocols or a path to a file that implements a protocol interface\. Defaults to \'AQ32\' driver\.
.
.IP "\(bu" 4
\fB[\-\-list]\fR
Returns json array of available ports given a communications driver\.
.
.IP "\(bu" 4
\fB[\-\-probe]\fR
Returns json array of available vehicles on all ports based on a heuristic\.
.
.IP "\(bu" 4
\fB[\-\-connect <uri>]\fR
Attempts connection to a given URI, or uses the first vehicle URI from a successful probe when used in combination with the \fB\-\-probe\fR option\.
.
.IP "\(bu" 4
\fB[\-\-subscribe <event>]\fR
Subscribe to an event and receive notifications, JSON output, newline delimited\.
.
.IP "\(bu" 4
\fB[\-\-sync <key> <value>]\fR
Read or write key data\. If a value is not specified, it is read from the vehicle\. To set a value provide the value in JSON\.
.
.IP "\(bu" 4
\fB[\-\-stream <key>]\fR
Streams real\-time state data from the vehicle for a given key\.
.
.IP "" 0
.
.SH "DEPENDENCIES"
This application is written in javascript using node\.js, and as such it requires a working node\.js environment\. Please see the project
page at (http://jleppert\.github\.io/nodequad/) for more information on making sure your node is properly working\.
.
.SH "DIRECTORIES"
Since this is just an npm module, it is typically installed according to what npm does\. You should refer to the npm documentation
for information on where this might be on your system\. If you installed it with the global option, it should be in your PATH and
generally can be run from anywhere\.
.
.SH "DEVELOPER USAGE"
Feel free to use this utility in any way that works for you\. However, this is mostly limited to simple functional tests and
rudimentary applications\. For more complicated use cases, consider using the nodequad object API from within a node\.js application\.
.
.SH "CONFIGURATION"
You can use the \fB\-\-driver\fR and \fB\-\-protocol\fR options to define a custom driver and protocol (or one of \fBNodequad\.drivers\fR, or \fBNodequad\.protocols\fR)\.
Either specify the key name or a path to a file that implements a suitable driver or protocol interface\.
.
.SH "BUGS"
If you\'ve found a bug, that\'s great! Please report it at: (http://github\.com/jleppert/nodequad/issues) and it will be promptly fixed\.
.
.SH "CONTRIBUTIONS"
Contributions are welcome and encouraged! Please see the project page at (http://jleppert\.github\.io/nodequad/) for more information on how to
contribute\.
.
.SH "AUTHOR"
Johnathan Leppert \fIhttps://github\.com/jleppert/\fR :: @iamleppert \fIhttp://twitter\.com/iamleppert\fR :: \fIjohnathan\.leppert@gmail\.com\fR
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
npm(1)
.
.IP "" 0
